### ISSUE TITLE
thread.LockType may not working as expected

### ISSUE THREAD

**Issue by S-YOU** [google/grumpy#250]
When I tried to add a unittest which use that.

```
fatal error: all goroutines are asleep - deadlock!

goroutine 1 [semacquire]:
sync.runtime_Semacquire(0xc42000b844)
	/usr/local/go/src/runtime/sema.go:47 +0x30
sync.(*Mutex).Lock(0xc42000b840)
	/usr/local/go/src/sync/mutex.go:85 +0xd0
reflect.Value.call(0xc42047bda0, 0xc4200a1720, 0x13, 0xb201bb, 0x4, 0xc420123540, 0x1, 0x1, 0x0, 0x0, ...)
	/usr/local/go/src/reflect/value.go:434 +0x5c8
reflect.Value.Call(0xc42047bda0, 0xc4200a1720, 0x13, 0xc420123540, 0x1, 0x1, 0x16, 0x0, 0x0)
	/usr/local/go/src/reflect/value.go:302 +0xa4
grumpy.nativeInvoke(0xc420325ce0, 0xc42047bda0, 0xc4200a1720, 0x13, 0xc4204a7940, 0x1, 0x1, 0xc420138758, 0x868be)
	/path/to/grumpy/build/src/grumpy/native.go:571 +0x3a3
grumpy.newNativeMethod.func1(0xc420325ce0, 0xc4204a7940, 0x1, 0x1, 0x0, 0x0, 0x0, 0x0, 0xa95a00)
	/path/to/grumpy/build/src/grumpy/native.go:468 +0x6a
grumpy.functionCall(0xc420325ce0, 0xc4202df8c0, 0xc4204a7940, 0x1, 0x1, 0x0, 0x0, 0x0, 0xc4204a7940, 0x9)
	/path/to/grumpy/build/src/grumpy/function.go:119 +0x11b
grumpy.(*Object).Call(0xc4202df8c0, 0xc420325ce0, 0xc4204a7940, 0x1, 0x1, 0x0, 0x0, 0x0, 0x112cfd, 0xc420325ce0)
	/path/to/grumpy/build/src/grumpy/object.go:64 +0xa3
grumpy.methodCall(0xc420325ce0, 0xc42037d540, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x30, 0x30)
	/path/to/grumpy/build/src/grumpy/method.go:68 +0x253
grumpy.(*Object).Call(0xc42037d540, 0xc420325ce0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc4201389c0)
	/path/to/grumpy/build/src/grumpy/object.go:64 +0xa3
grumpy/lib/thread.initModule.func2.2(0xc420325ce0, 0xc420040c30, 0x1, 0x6, 0x6, 0xc4204a7938)
	/path/to/grumpy/build/src/grumpy/lib/thread/module.go:251 +0x20a
grumpy.(*Code).Eval(0xc4200ef1a0, 0xc420325c70, 0xc42032c4c0, 0xc4204a7938, 0x1, 0x1, 0x0, 0x0, 0x0, 0xc420460000, ...)
	/path/to/grumpy/build/src/grumpy/code.go:66 +0x188
grumpy.functionCall(0xc420325c70, 0xc4203ea740, 0xc4204a7938, 0x1, 0x1, 0x0, 0x0, 0x0, 0xc4204a7938, 0xc42030c501)
	/path/to/grumpy/build/src/grumpy/function.go:121 +0x9a
grumpy.(*Object).Call(0xc4203ea740, 0xc420325c70, 0xc4204a7938, 0x1, 0x1, 0x0, 0x0, 0x0, 0x112cfd, 0xc420325c70)
	/path/to/grumpy/build/src/grumpy/object.go:64 +0xa3
grumpy.methodCall(0xc420325c70, 0xc42037d500, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x30, 0xa88bc0)
	/path/to/grumpy/build/src/grumpy/method.go:68 +0x253
grumpy.(*Object).Call(0xc42037d500, 0xc420325c70, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x1260e9, 0xc4200fe210)
	/path/to/grumpy/build/src/grumpy/object.go:64 +0xa3
grumpy/lib/thread.initModule.func2.4(0xc420325c70, 0xc420040c00, 0x1, 0x6, 0x6, 0xc4204a7930)
	/path/to/grumpy/build/src/grumpy/lib/thread/module.go:322 +0x1b6
grumpy.(*Code).Eval(0xc4200efe00, 0xc420325a40, 0xc42032c4c0, 0xc4204a7930, 0x1, 0x1, 0x0, 0x0, 0x0, 0xc4200710a0, ...)
	/path/to/grumpy/build/src/grumpy/code.go:66 +0x188
grumpy.functionCall(0xc420325a40, 0xc4203ea8c0, 0xc4204a7930, 0x1, 0x1, 0x0, 0x0, 0x0, 0xb, 0xc420138f10)
	/path/to/grumpy/build/src/grumpy/function.go:121 +0x9a
grumpy.(*Object).Call(0xc4203ea8c0, 0xc420325a40, 0xc4204a7930, 0x1, 0x1, 0x0, 0x0, 0x0, 0xc420325a40, 0xc4203ea8c0)
	/path/to/grumpy/build/src/grumpy/object.go:64 +0xa3
grumpy.methodCall(0xc420325a40, 0xc42037d4c0, 0xc4204a7930, 0x1, 0x1, 0x0, 0x0, 0x0, 0xc420139080, 0x870e8)
	/path/to/grumpy/build/src/grumpy/method.go:68 +0x253
grumpy.(*Object).Call(0xc42037d4c0, 0xc420325a40, 0xc4204a7930, 0x1, 0x1, 0x0, 0x0, 0x0, 0x0, 0xc4201234a0)
	/path/to/grumpy/build/src/grumpy/object.go:64 +0xa3
grumpy/lib/_strptime.initModule.func6(0xc420325a40, 0xc420040bd0, 0x2, 0x6, 0x6, 0xc420040ba0)
	/path/to/grumpy/build/src/grumpy/lib/_strptime/module.go:3057 +0x10356
grumpy.(*Code).Eval(0xc420120000, 0xc4203259d0, 0xc4204bebc0, 0xc420040ba0, 0x2, 0x6, 0x0, 0x0, 0x0, 0xc4200fe390, ...)
	/path/to/grumpy/build/src/grumpy/code.go:66 +0x188
grumpy.functionCall(0xc4203259d0, 0xc4202a7180, 0xc420040ba0, 0x2, 0x6, 0x0, 0x0, 0x0, 0xe04ed, 0xc42029c9a0)
	/path/to/grumpy/build/src/grumpy/function.go:121 +0x9a
grumpy.(*Object).Call(0xc4202a7180, 0xc4203259d0, 0xc420040ba0, 0x2, 0x6, 0x0, 0x0, 0x0, 0xe3354, 0xc42029c9a0)
	/path/to/grumpy/build/src/grumpy/object.go:64 +0xa3
grumpy/lib/_strptime.initModule.func7(0xc4203259d0, 0xc420040b70, 0x2, 0x6, 0x6, 0xc420040b10)
	/path/to/grumpy/build/src/grumpy/lib/_strptime/module.go:5161 +0x2e7
grumpy.(*Code).Eval(0xc420120420, 0xc42029c9a0, 0xc4204bebc0, 0xc420040b10, 0x2, 0x6, 0x0, 0x0, 0x0, 0xdbac3, ...)
	/path/to/grumpy/build/src/grumpy/code.go:66 +0x188
grumpy.functionCall(0xc42029c9a0, 0xc4202a7240, 0xc420040b10, 0x2, 0x6, 0x0, 0x0, 0x0, 0xdc444, 0xc42029c9a0)
	/path/to/grumpy/build/src/grumpy/function.go:121 +0x9a
grumpy.(*Object).Call(0xc4202a7240, 0xc42029c9a0, 0xc420040b10, 0x2, 0x6, 0x0, 0x0, 0x0, 0x0, 0xc4201234a0)
	/path/to/grumpy/build/src/grumpy/object.go:64 +0xa3
main.initModule.func4.2(0xc42029c9a0, 0xc4204448d0, 0x1, 0x6, 0x6, 0xc4204a61e8)
	/path/to/grumpy/a.go:3146 +0x102b
grumpy.(*Code).Eval(0xc4204fc840, 0xc42029c930, 0xc420217100, 0xc4204a61e8, 0x1, 0x1, 0x0, 0x0, 0x0, 0xc420460000, ...)
	/path/to/grumpy/build/src/grumpy/code.go:66 +0x188
grumpy.functionCall(0xc42029c930, 0xc4200d37c0, 0xc4204a61e8, 0x1, 0x1, 0x0, 0x0, 0x0, 0xc4204a61e8, 0x0)
	/path/to/grumpy/build/src/grumpy/function.go:121 +0x9a
grumpy.(*Object).Call(0xc4200d37c0, 0xc42029c930, 0xc4204a61e8, 0x1, 0x1, 0x0, 0x0, 0x0, 0xde62e0, 0x0)
	/path/to/grumpy/build/src/grumpy/object.go:64 +0xa3
grumpy.methodCall(0xc42029c930, 0xc42041e9c0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xde62e0, 0x0)
	/path/to/grumpy/build/src/grumpy/method.go:68 +0x253
grumpy.(*Object).Call(0xc42041e9c0, 0xc42029c930, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xde62e0, 0x0)
	/path/to/grumpy/build/src/grumpy/object.go:64 +0xa3
grumpy/lib/unittest_case.initModule.func11.18(0xc42029c930, 0xc4204448a0, 0x2, 0x6, 0x6, 0xc420425270)
	/path/to/grumpy/build/src/grumpy/lib/unittest_case/module.go:3334 +0x30fc
grumpy.(*Code).Eval(0xc420198480, 0xc42029c8c0, 0xc4203eea00, 0xc420425270, 0x2, 0x2, 0xe03c60, 0x0, 0x0, 0xc420460000, ...)
	/path/to/grumpy/build/src/grumpy/code.go:66 +0x188
grumpy.functionCall(0xc42029c8c0, 0xc42019a7c0, 0xc420425270, 0x2, 0x2, 0xe03c60, 0x0, 0x0, 0xc420425278, 0xc4201b7340)
	/path/to/grumpy/build/src/grumpy/function.go:121 +0x9a
grumpy.(*Object).Call(0xc42019a7c0, 0xc42029c8c0, 0xc420425270, 0x2, 0x2, 0xe03c60, 0x0, 0x0, 0x0, 0xc42013aa18)
	/path/to/grumpy/build/src/grumpy/object.go:64 +0xa3
grumpy.methodCall(0xc42029c8c0, 0xc42041e540, 0xc4204a60d0, 0x1, 0x1, 0xe03c60, 0x0, 0x0, 0xc4201b7340, 0xc420079340)
	/path/to/grumpy/build/src/grumpy/method.go:68 +0x253
grumpy.(*Object).Call(0xc42041e540, 0xc42029c8c0, 0xc4204a60d0, 0x1, 0x1, 0xe03c60, 0x0, 0x0, 0xc42029c8c0, 0xc420475e40)
	/path/to/grumpy/build/src/grumpy/object.go:64 +0xa3
grumpy.Invoke(0xc42029c8c0, 0xc42041e540, 0xc4204a60d0, 0x1, 0x1, 0xc4201148a0, 0xe03c60, 0x0, 0x0, 0xc42041e500, ...)
	/path/to/grumpy/build/src/grumpy/core.go:599 +0xd8
grumpy/lib/unittest_case.initModule.func11.20(0xc42029c8c0, 0xc420444600, 0x3, 0x6, 0x6, 0xc420425250)
	/path/to/grumpy/build/src/grumpy/lib/unittest_case/module.go:4287 +0x294
grumpy.(*Code).Eval(0xc420198540, 0xc42029c700, 0xc4203eea00, 0xc420425250, 0x2, 0x2, 0x0, 0x0, 0x0, 0xc420460000, ...)
	/path/to/grumpy/build/src/grumpy/code.go:66 +0x188
grumpy.functionCall(0xc42029c700, 0xc42019a940, 0xc420425250, 0x2, 0x2, 0x0, 0x0, 0x0, 0xc420425258, 0x0)
	/path/to/grumpy/build/src/grumpy/function.go:121 +0x9a
grumpy.(*Object).Call(0xc42019a940, 0xc42029c700, 0xc420425250, 0x2, 0x2, 0x0, 0x0, 0x0, 0x0, 0x0)
	/path/to/grumpy/build/src/grumpy/object.go:64 +0xa3
grumpy.(*callSlot).wrapCallable.func1(0xc42029c700, 0xc420475e40, 0xc4204445d0, 0x1, 0x6, 0x0, 0x0, 0x0, 0xde6500, 0x0)
	/path/to/grumpy/build/src/grumpy/slots.go:92 +0x153
grumpy.(*Object).Call(0xc420475e40, 0xc42029c700, 0xc4204445d0, 0x1, 0x6, 0x0, 0x0, 0x0, 0xde6500, 0x0)
	/path/to/grumpy/build/src/grumpy/object.go:64 +0xa3
grumpy/lib/unittest_suite.initModule.func3.1(0xc42029c700, 0xc4204445a0, 0x3, 0x6, 0x6, 0xc420425100)
	/path/to/grumpy/build/src/grumpy/lib/unittest_suite/module.go:1576 +0x173f
grumpy.(*Code).Eval(0xc420316a20, 0xc42029c690, 0xc4201a1680, 0xc420425100, 0x2, 0x2, 0xe03c60, 0x0, 0x0, 0xc420460000, ...)
	/path/to/grumpy/build/src/grumpy/code.go:66 +0x188
grumpy.functionCall(0xc42029c690, 0xc42033e180, 0xc420425100, 0x2, 0x2, 0xe03c60, 0x0, 0x0, 0xc420425108, 0xc4201b7220)
	/path/to/grumpy/build/src/grumpy/function.go:121 +0x9a
grumpy.(*Object).Call(0xc42033e180, 0xc42029c690, 0xc420425100, 0x2, 0x2, 0xe03c60, 0x0, 0x0, 0x0, 0xc42013b358)
	/path/to/grumpy/build/src/grumpy/object.go:64 +0xa3
grumpy.methodCall(0xc42029c690, 0xc42029bc40, 0xc4204a6030, 0x1, 0x1, 0xe03c60, 0x0, 0x0, 0xc4201b7220, 0xc420079340)
	/path/to/grumpy/build/src/grumpy/method.go:68 +0x253
grumpy.(*Object).Call(0xc42029bc40, 0xc42029c690, 0xc4204a6030, 0x1, 0x1, 0xe03c60, 0x0, 0x0, 0xc42029c690, 0xc42043bac0)
	/path/to/grumpy/build/src/grumpy/object.go:64 +0xa3
grumpy.Invoke(0xc42029c690, 0xc42029bc40, 0xc4204a6030, 0x1, 0x1, 0xc420114210, 0xe03c60, 0x0, 0x0, 0xc42029bc00, ...)
	/path/to/grumpy/build/src/grumpy/core.go:599 +0xd8
grumpy/lib/unittest_suite.initModule.func2.10(0xc42029c690, 0xc420444570, 0x3, 0x6, 0x6, 0xc4204250f0)
	/path/to/grumpy/build/src/grumpy/lib/unittest_suite/module.go:1111 +0x294
grumpy.(*Code).Eval(0xc4203168a0, 0xc420295c70, 0xc4201a1680, 0xc4204250f0, 0x2, 0x2, 0x0, 0x0, 0x0, 0xc420460000, ...)
	/path/to/grumpy/build/src/grumpy/code.go:66 +0x188
grumpy.functionCall(0xc420295c70, 0xc4201a1f80, 0xc4204250f0, 0x2, 0x2, 0x0, 0x0, 0x0, 0xc4204250f8, 0x0)
	/path/to/grumpy/build/src/grumpy/function.go:121 +0x9a
grumpy.(*Object).Call(0xc4201a1f80, 0xc420295c70, 0xc4204250f0, 0x2, 0x2, 0x0, 0x0, 0x0, 0x6, 0x0)
	/path/to/grumpy/build/src/grumpy/object.go:64 +0xa3
grumpy.(*callSlot).wrapCallable.func1(0xc420295c70, 0xc42043bac0, 0xc4203d1f80, 0x1, 0x6, 0x0, 0x0, 0x0, 0xde6500, 0x0)
	/path/to/grumpy/build/src/grumpy/slots.go:92 +0x153
grumpy.(*Object).Call(0xc42043bac0, 0xc420295c70, 0xc4203d1f80, 0x1, 0x6, 0x0, 0x0, 0x0, 0xde6500, 0x0)
	/path/to/grumpy/build/src/grumpy/object.go:64 +0xa3
grumpy/lib/unittest_suite.initModule.func3.1(0xc420295c70, 0xc420389890, 0x3, 0x6, 0x6, 0xc420081ec0)
	/path/to/grumpy/build/src/grumpy/lib/unittest_suite/module.go:1576 +0x173f
grumpy.(*Code).Eval(0xc420316a20, 0xc420295c00, 0xc4201a1680, 0xc420081ec0, 0x2, 0x2, 0xe03c60, 0x0, 0x0, 0xc420054000, ...)
	/path/to/grumpy/build/src/grumpy/code.go:66 +0x188
grumpy.functionCall(0xc420295c00, 0xc42033e180, 0xc420081ec0, 0x2, 0x2, 0xe03c60, 0x0, 0x0, 0xc420081ec8, 0xc10c0)
	/path/to/grumpy/build/src/grumpy/function.go:121 +0x9a
grumpy.(*Object).Call(0xc42033e180, 0xc420295c00, 0xc420081ec0, 0x2, 0x2, 0xe03c60, 0x0, 0x0, 0x0, 0xc420133cb8)
	/path/to/grumpy/build/src/grumpy/object.go:64 +0xa3
grumpy.methodCall(0xc420295c00, 0xc42022ae00, 0xc4200a0998, 0x1, 0x1, 0xe03c60, 0x0, 0x0, 0xc420217190, 0x0)
	/path/to/grumpy/build/src/grumpy/method.go:68 +0x253
grumpy.(*Object).Call(0xc42022ae00, 0xc420295c00, 0xc4200a0998, 0x1, 0x1, 0xe03c60, 0x0, 0x0, 0xc420295c00, 0xc42036a480)
	/path/to/grumpy/build/src/grumpy/object.go:64 +0xa3
grumpy.Invoke(0xc420295c00, 0xc42022ae00, 0xc4200a0998, 0x1, 0x1, 0xc4204949c0, 0xe03c60, 0x0, 0x0, 0xc42022adc0, ...)
	/path/to/grumpy/build/src/grumpy/core.go:599 +0xd8
grumpy/lib/unittest_suite.initModule.func2.10(0xc420295c00, 0xc420389860, 0x3, 0x6, 0x6, 0xc420081eb0)
	/path/to/grumpy/build/src/grumpy/lib/unittest_suite/module.go:1111 +0x294
grumpy.(*Code).Eval(0xc4203168a0, 0xc420295b90, 0xc4201a1680, 0xc420081eb0, 0x2, 0x2, 0x0, 0x0, 0x0, 0xc420054000, ...)
	/path/to/grumpy/build/src/grumpy/code.go:66 +0x188
grumpy.functionCall(0xc420295b90, 0xc4201a1f80, 0xc420081eb0, 0x2, 0x2, 0x0, 0x0, 0x0, 0xc420081eb8, 0xc10c0)
	/path/to/grumpy/build/src/grumpy/function.go:121 +0x9a
grumpy.(*Object).Call(0xc4201a1f80, 0xc420295b90, 0xc420081eb0, 0x2, 0x2, 0x0, 0x0, 0x0, 0xe447f, 0xc4200daa50)
	/path/to/grumpy/build/src/grumpy/object.go:64 +0xa3
grumpy.(*callSlot).wrapCallable.func1(0xc420295b90, 0xc42036a480, 0xc420388120, 0x1, 0x6, 0x0, 0x0, 0x0, 0x87a5d, 0xc420388120)
	/path/to/grumpy/build/src/grumpy/slots.go:92 +0x153
grumpy.(*Object).Call(0xc42036a480, 0xc420295b90, 0xc420388120, 0x1, 0x6, 0x0, 0x0, 0x0, 0xde62e0, 0x0)
	/path/to/grumpy/build/src/grumpy/object.go:64 +0xa3
grumpy/lib/unittest_runner.initModule.func3.3(0xc420295b90, 0xc42022aa80, 0x2, 0x7, 0x7, 0xc420081ea0)
	/path/to/grumpy/build/src/grumpy/lib/unittest_runner/module.go:2609 +0x7bcd
grumpy.(*Code).Eval(0xc420432600, 0xc420295b20, 0xc420111800, 0xc420081ea0, 0x2, 0x2, 0x0, 0x0, 0x0, 0xc420054000, ...)
	/path/to/grumpy/build/src/grumpy/code.go:66 +0x188
grumpy.functionCall(0xc420295b20, 0xc420371e00, 0xc420081ea0, 0x2, 0x2, 0x0, 0x0, 0x0, 0xc420081ea8, 0xc10c0)
	/path/to/grumpy/build/src/grumpy/function.go:121 +0x9a
grumpy.(*Object).Call(0xc420371e00, 0xc420295b20, 0xc420081ea0, 0x2, 0x2, 0x0, 0x0, 0x0, 0x112cfd, 0xc420295b20)
	/path/to/grumpy/build/src/grumpy/object.go:64 +0xa3
grumpy.methodCall(0xc420295b20, 0xc42022ab40, 0xc4203880f0, 0x1, 0x6, 0x0, 0x0, 0x0, 0x87a5d, 0xc4203880f0)
	/path/to/grumpy/build/src/grumpy/method.go:68 +0x253
grumpy.(*Object).Call(0xc42022ab40, 0xc420295b20, 0xc4203880f0, 0x1, 0x6, 0x0, 0x0, 0x0, 0xc4202289e0, 0x0)
	/path/to/grumpy/build/src/grumpy/object.go:64 +0xa3
grumpy/lib/test/test_support.initModule.func12(0xc420295b20, 0xc4204bffc0, 0x1, 0x7, 0x7, 0xc420388090)
	/path/to/grumpy/build/src/grumpy/lib/test/test_support/module.go:2867 +0x6a7
grumpy.(*Code).Eval(0xc420120ba0, 0xc420294000, 0xc4202c6280, 0xc420388090, 0x1, 0x6, 0x0, 0x0, 0x0, 0xc420204840, ...)
	/path/to/grumpy/build/src/grumpy/code.go:66 +0x188
grumpy.functionCall(0xc420294000, 0xc4204bea80, 0xc420388090, 0x1, 0x6, 0x0, 0x0, 0x0, 0x87a5d, 0xc420388090)
	/path/to/grumpy/build/src/grumpy/function.go:121 +0x9a
grumpy.(*Object).Call(0xc4204bea80, 0xc420294000, 0xc420388090, 0x1, 0x6, 0x0, 0x0, 0x0, 0xde62e0, 0x0)
	/path/to/grumpy/build/src/grumpy/object.go:64 +0xa3
grumpy/lib/test/test_support.initModule.func13(0xc420294000, 0xc420388060, 0x1, 0x6, 0x6, 0xc420321dc0)
	/path/to/grumpy/build/src/grumpy/lib/test/test_support/module.go:3362 +0x1f25
grumpy.(*Code).Eval(0xc420120c00, 0xc4200a9f80, 0xc4202c6280, 0xc420321dc0, 0x8, 0x8, 0x0, 0x0, 0x0, 0xdbac3, ...)
	/path/to/grumpy/build/src/grumpy/code.go:66 +0x188
grumpy.functionCall(0xc4200a9f80, 0xc4204beb40, 0xc420321dc0, 0x8, 0x8, 0x0, 0x0, 0x0, 0xc420321dc0, 0x0)
	/path/to/grumpy/build/src/grumpy/function.go:121 +0x9a
grumpy.(*Object).Call(0xc4204beb40, 0xc4200a9f80, 0xc420321dc0, 0x8, 0x8, 0x0, 0x0, 0x0, 0x1260e9, 0xc4200ff170)
	/path/to/grumpy/build/src/grumpy/object.go:64 +0xa3
main.initModule.func9(0xc4200a9f80, 0x0, 0x0, 0x0, 0x0, 0x0)
	/path/to/grumpy/a.go:8949 +0x580
grumpy.(*Code).Eval(0xc4204fdb00, 0xc4200680e0, 0xc420217100, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc4200ff170, ...)
	/path/to/grumpy/build/src/grumpy/code.go:66 +0x188
grumpy.functionCall(0xc4200680e0, 0xc420321d80, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc4200680e0, 0x2)
	/path/to/grumpy/build/src/grumpy/function.go:121 +0x9a
grumpy.(*Object).Call(0xc420321d80, 0xc4200680e0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc4204fdaa0, 0xc4204fdb00)
	/path/to/grumpy/build/src/grumpy/object.go:64 +0xa3
main.initModule(0xc4200680e0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/path/to/grumpy/a.go:8981 +0x76e8
grumpy.(*Code).Eval(0xc42006f4a0, 0xc420068070, 0xc420217100, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x870e8, ...)
	/path/to/grumpy/build/src/grumpy/code.go:66 +0x188
grumpy.RunMain(0xc42006f4a0, 0x0)
	/path/to/grumpy/build/src/grumpy/module.go:294 +0x1f8
```

**Comment by trotterdylan** [comment]
This may be a legit deadlock caused by the Python code. What does _strptime.py look like?

**Comment by S-YOU** [comment]
I dropped _strptime.py from datetime PR, don't have that anymore at the moment. Will try to add it again later.

**Comment by trotterdylan** [comment]
There were some deadlock issues caused by code that failed to release mutexes during thread shutdown because of spurious exceptions being raised, e.g. https://github.com/google/grumpy/pull/345

I'm not sure how to reproduce this exact issue, but I suspect it's been fixed along the way.
