### ISSUE TITLE
dictNE checks type of wrong arg resulting in unsafe cast to dict

### ISSUE THREAD

**Issue by S-YOU** [google/grumpy#251]
No idea, what cause this, when I trying to add a test from test_datetime.py

```
test_compare (__main__.TestDate) ... panic: sync: inconsistent mutex state

goroutine 1 [running]:
panic(0xc19680, 0xc42040e060)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
sync.(*Mutex).Lock(0xc4203c92c0)
	/usr/local/go/src/sync/mutex.go:77 +0x136
grumpy.(*recursiveMutex).Lock(0xc4203c92c0, 0xc4204d2e70)
	/path/to/grumpy/build/src/grumpy/threading.go:62 +0x75
grumpy.dictsAreEqual(0xc4204d2e70, 0xc4202e99c0, 0xc4203c92a0, 0xff, 0xc4200d4540)
	/path/to/grumpy/build/src/grumpy/dict.go:492 +0x13c
grumpy.dictNE(0xc4204d2e70, 0xc4202e99c0, 0xc4203c92a0, 0x2cbdb3, 0xc4204d2e70)
	/path/to/grumpy/build/src/grumpy/dict.go:711 +0x66
grumpy.tryRichCompare(0xc4204d2e70, 0x3, 0xc4202e99c0, 0xc4203c92a0, 0x6, 0x0)
	/path/to/grumpy/build/src/grumpy/core.go:1056 +0x12c
grumpy.compareRich(0xc4204d2e70, 0x3, 0xc4202e99c0, 0xc4203c92a0, 0x1028520, 0x0)
	/path/to/grumpy/build/src/grumpy/core.go:987 +0x4d
grumpy.NE(0xc4204d2e70, 0xc4202e99c0, 0xc4203c92a0, 0x2, 0x0)
	/path/to/grumpy/build/src/grumpy/core.go:604 +0x4c
main.initModule.func9.22(0xc4204d2e70, 0xc42015be00, 0x1, 0x6, 0x6, 0xc4201b0558)
	/path/to/grumpy/a.go:18038 +0x6068
grumpy.(*Code).Eval(0xc4204e6ba0, 0xc4204d2e00, 0xc420233100, 0xc4201b0558, 0x1, 0x1, 0x0, 0x0, 0x0, 0xc420056000, ...)
	/path/to/grumpy/build/src/grumpy/code.go:66 +0x188
grumpy.functionCall(0xc4204d2e00, 0xc4204e3340, 0xc4201b0558, 0x1, 0x1, 0x0, 0x0, 0x0, 0xc4201b0558, 0x0)
	/path/to/grumpy/build/src/grumpy/function.go:121 +0x9a
grumpy.(*Object).Call(0xc4204e3340, 0xc4204d2e00, 0xc4201b0558, 0x1, 0x1, 0x0, 0x0, 0x0, 0x10282f0, 0x0)
	/path/to/grumpy/build/src/grumpy/object.go:64 +0xa3
grumpy.methodCall(0xc4204d2e00, 0xc4202c3d00, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x10282f0, 0x0)
	/path/to/grumpy/build/src/grumpy/method.go:68 +0x253
grumpy.(*Object).Call(0xc4202c3d00, 0xc4204d2e00, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x10282f0, 0x0)
	/path/to/grumpy/build/src/grumpy/object.go:64 +0xa3
grumpy/lib/unittest_case.initModule.func11.18(0xc4204d2e00, 0xc42015bdd0, 0x2, 0x6, 0x6, 0xc420180a20)
	/path/to/grumpy/build/src/grumpy/lib/unittest_case/module.go:3334 +0x30fc
grumpy.(*Code).Eval(0xc4200a24e0, 0xc4204d2d90, 0xc4202fea00, 0xc420180a20, 0x2, 0x2, 0x1045c80, 0x0, 0x0, 0xc420056000, ...)
	/path/to/grumpy/build/src/grumpy/code.go:66 +0x188
grumpy.functionCall(0xc4204d2d90, 0xc4200a4800, 0xc420180a20, 0x2, 0x2, 0x1045c80, 0x0, 0x0, 0xc420180a28, 0xc4203c90a0)
	/path/to/grumpy/build/src/grumpy/function.go:121 +0x9a
grumpy.(*Object).Call(0xc4200a4800, 0xc4204d2d90, 0xc420180a20, 0x2, 0x2, 0x1045c80, 0x0, 0x0, 0x0, 0xc420199818)
	/path/to/grumpy/build/src/grumpy/object.go:64 +0xa3
grumpy.methodCall(0xc4204d2d90, 0xc4202c3840, 0xc4201b04c0, 0x1, 0x1, 0x1045c80, 0x0, 0x0, 0xc4203c90a0, 0xc420075340)
	/path/to/grumpy/build/src/grumpy/method.go:68 +0x253
grumpy.(*Object).Call(0xc4202c3840, 0xc4204d2d90, 0xc4201b04c0, 0x1, 0x1, 0x1045c80, 0x0, 0x0, 0xc4204d2d90, 0xc4202f3100)
	/path/to/grumpy/build/src/grumpy/object.go:64 +0xa3
grumpy.Invoke(0xc4204d2d90, 0xc4202c3840, 0xc4201b04c0, 0x1, 0x1, 0xc4204d58f0, 0x1045c80, 0x0, 0x0, 0xc4202c3800, ...)
	/path/to/grumpy/build/src/grumpy/core.go:599 +0xd8
grumpy/lib/unittest_case.initModule.func11.20(0xc4204d2d90, 0xc42015b3e0, 0x3, 0x6, 0x6, 0xc420180a10)
	/path/to/grumpy/build/src/grumpy/lib/unittest_case/module.go:4287 +0x294
grumpy.(*Code).Eval(0xc4200a25a0, 0xc4204cf030, 0xc4202fea00, 0xc420180a10, 0x2, 0x2, 0x0, 0x0, 0x0, 0xc420056000, ...)
	/path/to/grumpy/build/src/grumpy/code.go:66 +0x188
grumpy.functionCall(0xc4204cf030, 0xc4200a4980, 0xc420180a10, 0x2, 0x2, 0x0, 0x0, 0x0, 0xc420180a18, 0x0)
	/path/to/grumpy/build/src/grumpy/function.go:121 +0x9a
grumpy.(*Object).Call(0xc4200a4980, 0xc4204cf030, 0xc420180a10, 0x2, 0x2, 0x0, 0x0, 0x0, 0x0, 0x0)
	/path/to/grumpy/build/src/grumpy/object.go:64 +0xa3
grumpy.(*callSlot).wrapCallable.func1(0xc4204cf030, 0xc4202f3100, 0xc42015b3b0, 0x1, 0x6, 0x0, 0x0, 0x0, 0x1028520, 0x0)
	/path/to/grumpy/build/src/grumpy/slots.go:92 +0x153
grumpy.(*Object).Call(0xc4202f3100, 0xc4204cf030, 0xc42015b3b0, 0x1, 0x6, 0x0, 0x0, 0x0, 0x1028520, 0x0)
	/path/to/grumpy/build/src/grumpy/object.go:64 +0xa3
grumpy/lib/unittest_suite.initModule.func3.1(0xc4204cf030, 0xc42015b380, 0x3, 0x6, 0x6, 0xc420417f20)
	/path/to/grumpy/build/src/grumpy/lib/unittest_suite/module.go:1576 +0x173f
grumpy.(*Code).Eval(0xc42014ea80, 0xc4204cefc0, 0xc4200a96c0, 0xc420417f20, 0x2, 0x2, 0x1045c80, 0x0, 0x0, 0xc420056000, ...)
	/path/to/grumpy/build/src/grumpy/code.go:66 +0x188
grumpy.functionCall(0xc4204cefc0, 0xc4204c61c0, 0xc420417f20, 0x2, 0x2, 0x1045c80, 0x0, 0x0, 0xc420417f28, 0xc4203c0120)
	/path/to/grumpy/build/src/grumpy/function.go:121 +0x9a
grumpy.(*Object).Call(0xc4204c61c0, 0xc4204cefc0, 0xc420417f20, 0x2, 0x2, 0x1045c80, 0x0, 0x0, 0x0, 0xc42019a158)
	/path/to/grumpy/build/src/grumpy/object.go:64 +0xa3
grumpy.methodCall(0xc4204cefc0, 0xc42024f6c0, 0xc420029b80, 0x1, 0x1, 0x1045c80, 0x0, 0x0, 0xc4203c0120, 0xc420075340)
	/path/to/grumpy/build/src/grumpy/method.go:68 +0x253
grumpy.(*Object).Call(0xc42024f6c0, 0xc4204cefc0, 0xc420029b80, 0x1, 0x1, 0x1045c80, 0x0, 0x0, 0xc4204cefc0, 0xc4203c8420)
	/path/to/grumpy/build/src/grumpy/object.go:64 +0xa3
grumpy.Invoke(0xc4204cefc0, 0xc42024f6c0, 0xc420029b80, 0x1, 0x1, 0xc4202b4540, 0x1045c80, 0x0, 0x0, 0xc42024f680, ...)
	/path/to/grumpy/build/src/grumpy/core.go:599 +0xd8
grumpy/lib/unittest_suite.initModule.func2.10(0xc4204cefc0, 0xc42015b350, 0x3, 0x6, 0x6, 0xc420417f10)
	/path/to/grumpy/build/src/grumpy/lib/unittest_suite/module.go:1111 +0x294
grumpy.(*Code).Eval(0xc42014e900, 0xc42004db90, 0xc4200a96c0, 0xc420417f10, 0x2, 0x2, 0x0, 0x0, 0x0, 0xc420056000, ...)
	/path/to/grumpy/build/src/grumpy/code.go:66 +0x188
grumpy.functionCall(0xc42004db90, 0xc4200a9fc0, 0xc420417f10, 0x2, 0x2, 0x0, 0x0, 0x0, 0xc420417f18, 0x0)
	/path/to/grumpy/build/src/grumpy/function.go:121 +0x9a
grumpy.(*Object).Call(0xc4200a9fc0, 0xc42004db90, 0xc420417f10, 0x2, 0x2, 0x0, 0x0, 0x0, 0x6, 0x0)
	/path/to/grumpy/build/src/grumpy/object.go:64 +0xa3
grumpy.(*callSlot).wrapCallable.func1(0xc42004db90, 0xc4203c8420, 0xc42015ac00, 0x1, 0x6, 0x0, 0x0, 0x0, 0x1028520, 0x0)
	/path/to/grumpy/build/src/grumpy/slots.go:92 +0x153
grumpy.(*Object).Call(0xc4203c8420, 0xc42004db90, 0xc42015ac00, 0x1, 0x6, 0x0, 0x0, 0x0, 0x1028520, 0x0)
	/path/to/grumpy/build/src/grumpy/object.go:64 +0xa3
grumpy/lib/unittest_suite.initModule.func3.1(0xc42004db90, 0xc42021f380, 0x3, 0x6, 0x6, 0xc42040eb30)
	/path/to/grumpy/build/src/grumpy/lib/unittest_suite/module.go:1576 +0x173f
grumpy.(*Code).Eval(0xc42014ea80, 0xc42004db20, 0xc4200a96c0, 0xc42040eb30, 0x2, 0x2, 0x1045c80, 0x0, 0x0, 0xc420056400, ...)
	/path/to/grumpy/build/src/grumpy/code.go:66 +0x188
grumpy.functionCall(0xc42004db20, 0xc4204c61c0, 0xc42040eb30, 0x2, 0x2, 0x1045c80, 0x0, 0x0, 0xc42040eb38, 0xc4203c03c0)
	/path/to/grumpy/build/src/grumpy/function.go:121 +0x9a
grumpy.(*Object).Call(0xc4204c61c0, 0xc42004db20, 0xc42040eb30, 0x2, 0x2, 0x1045c80, 0x0, 0x0, 0x0, 0xc420254ab8)
	/path/to/grumpy/build/src/grumpy/object.go:64 +0xa3
grumpy.methodCall(0xc42004db20, 0xc4203bfe00, 0xc4201b1440, 0x1, 0x1, 0x1045c80, 0x0, 0x0, 0xc4203c03c0, 0xc420075340)
	/path/to/grumpy/build/src/grumpy/method.go:68 +0x253
grumpy.(*Object).Call(0xc4203bfe00, 0xc42004db20, 0xc4201b1440, 0x1, 0x1, 0x1045c80, 0x0, 0x0, 0xc42004db20, 0xc42026dd40)
	/path/to/grumpy/build/src/grumpy/object.go:64 +0xa3
grumpy.Invoke(0xc42004db20, 0xc4203bfe00, 0xc4201b1440, 0x1, 0x1, 0xc42026baa0, 0x1045c80, 0x0, 0x0, 0xc4203bfdc0, ...)
	/path/to/grumpy/build/src/grumpy/core.go:599 +0xd8
grumpy/lib/unittest_suite.initModule.func2.10(0xc42004db20, 0xc42021f1d0, 0x3, 0x6, 0x6, 0xc42040eb20)
	/path/to/grumpy/build/src/grumpy/lib/unittest_suite/module.go:1111 +0x294
grumpy.(*Code).Eval(0xc42014e900, 0xc42004dab0, 0xc4200a96c0, 0xc42040eb20, 0x2, 0x2, 0x0, 0x0, 0x0, 0xc420056400, ...)
	/path/to/grumpy/build/src/grumpy/code.go:66 +0x188
grumpy.functionCall(0xc42004dab0, 0xc4200a9fc0, 0xc42040eb20, 0x2, 0x2, 0x0, 0x0, 0x0, 0xc42040eb28, 0x0)
	/path/to/grumpy/build/src/grumpy/function.go:121 +0x9a
grumpy.(*Object).Call(0xc4200a9fc0, 0xc42004dab0, 0xc42040eb20, 0x2, 0x2, 0x0, 0x0, 0x0, 0x6, 0x0)
	/path/to/grumpy/build/src/grumpy/object.go:64 +0xa3
grumpy.(*callSlot).wrapCallable.func1(0xc42004dab0, 0xc42026dd40, 0xc4204351a0, 0x1, 0x6, 0x0, 0x0, 0x0, 0x1028520, 0x0)
	/path/to/grumpy/build/src/grumpy/slots.go:92 +0x153
grumpy.(*Object).Call(0xc42026dd40, 0xc42004dab0, 0xc4204351a0, 0x1, 0x6, 0x0, 0x0, 0x0, 0x1028520, 0x0)
	/path/to/grumpy/build/src/grumpy/object.go:64 +0xa3
grumpy/lib/unittest_suite.initModule.func3.1(0xc42004dab0, 0xc420434fc0, 0x3, 0x6, 0x6, 0xc42040eb00)
	/path/to/grumpy/build/src/grumpy/lib/unittest_suite/module.go:1576 +0x173f
grumpy.(*Code).Eval(0xc42014ea80, 0xc42004d9d0, 0xc4200a96c0, 0xc42040eb00, 0x2, 0x2, 0x1045c80, 0x0, 0x0, 0xc420056400, ...)
	/path/to/grumpy/build/src/grumpy/code.go:66 +0x188
grumpy.functionCall(0xc42004d9d0, 0xc4204c61c0, 0xc42040eb00, 0x2, 0x2, 0x1045c80, 0x0, 0x0, 0xc42040eb08, 0xc4203c0380)
	/path/to/grumpy/build/src/grumpy/function.go:121 +0x9a
grumpy.(*Object).Call(0xc4204c61c0, 0xc42004d9d0, 0xc42040eb00, 0x2, 0x2, 0x1045c80, 0x0, 0x0, 0x0, 0xc4202553f8)
	/path/to/grumpy/build/src/grumpy/object.go:64 +0xa3
grumpy.methodCall(0xc42004d9d0, 0xc4203bfc80, 0xc4201b1420, 0x1, 0x1, 0x1045c80, 0x0, 0x0, 0xc4203c0380, 0xc420075340)
	/path/to/grumpy/build/src/grumpy/method.go:68 +0x253
grumpy.(*Object).Call(0xc4203bfc80, 0xc42004d9d0, 0xc4201b1420, 0x1, 0x1, 0x1045c80, 0x0, 0x0, 0xc42004d9d0, 0xc420346280)
	/path/to/grumpy/build/src/grumpy/object.go:64 +0xa3
grumpy.Invoke(0xc42004d9d0, 0xc4203bfc80, 0xc4201b1420, 0x1, 0x1, 0xc42026b980, 0x1045c80, 0x0, 0x0, 0xc4203bfc40, ...)
	/path/to/grumpy/build/src/grumpy/core.go:599 +0xd8
grumpy/lib/unittest_suite.initModule.func2.10(0xc42004d9d0, 0xc4204aa180, 0x3, 0x6, 0x6, 0xc42040eaf0)
	/path/to/grumpy/build/src/grumpy/lib/unittest_suite/module.go:1111 +0x294
grumpy.(*Code).Eval(0xc42014e900, 0xc42004d960, 0xc4200a96c0, 0xc42040eaf0, 0x2, 0x2, 0x0, 0x0, 0x0, 0xc420056400, ...)
	/path/to/grumpy/build/src/grumpy/code.go:66 +0x188
grumpy.functionCall(0xc42004d960, 0xc4200a9fc0, 0xc42040eaf0, 0x2, 0x2, 0x0, 0x0, 0x0, 0xc42040eaf8, 0x10282f0)
	/path/to/grumpy/build/src/grumpy/function.go:121 +0x9a
grumpy.(*Object).Call(0xc4200a9fc0, 0xc42004d960, 0xc42040eaf0, 0x2, 0x2, 0x0, 0x0, 0x0, 0x2d476f, 0xc420318a50)
	/path/to/grumpy/build/src/grumpy/object.go:64 +0xa3
grumpy.(*callSlot).wrapCallable.func1(0xc42004d960, 0xc420346280, 0xc4204aa150, 0x1, 0x6, 0x0, 0x0, 0x0, 0xc42040ead8, 0x0)
	/path/to/grumpy/build/src/grumpy/slots.go:92 +0x153
grumpy.(*Object).Call(0xc420346280, 0xc42004d960, 0xc4204aa150, 0x1, 0x6, 0x0, 0x0, 0x0, 0x10282f0, 0x0)
	/path/to/grumpy/build/src/grumpy/object.go:64 +0xa3
grumpy/lib/unittest_runner.initModule.func3.3(0xc42004d960, 0xc4203bf900, 0x2, 0x7, 0x7, 0xc42040eac0)
	/path/to/grumpy/build/src/grumpy/lib/unittest_runner/module.go:2609 +0x7bcd
grumpy.(*Code).Eval(0xc42014ee40, 0xc42004d8f0, 0xc4202b6200, 0xc42040eac0, 0x2, 0x2, 0x0, 0x0, 0x0, 0xc420056400, ...)
	/path/to/grumpy/build/src/grumpy/code.go:66 +0x188
grumpy.functionCall(0xc42004d8f0, 0xc420287f00, 0xc42040eac0, 0x2, 0x2, 0x0, 0x0, 0x0, 0xc42040eac8, 0xc4202fdc01)
	/path/to/grumpy/build/src/grumpy/function.go:121 +0x9a
grumpy.(*Object).Call(0xc420287f00, 0xc42004d8f0, 0xc42040eac0, 0x2, 0x2, 0x0, 0x0, 0x0, 0x302fed, 0xc42004d8f0)
	/path/to/grumpy/build/src/grumpy/object.go:64 +0xa3
grumpy.methodCall(0xc42004d8f0, 0xc4203bf9c0, 0xc4203fd2c0, 0x1, 0x7, 0x0, 0x0, 0x0, 0xc42026de20, 0x0)
	/path/to/grumpy/build/src/grumpy/method.go:68 +0x253
grumpy.(*Object).Call(0xc4203bf9c0, 0xc42004d8f0, 0xc4203fd2c0, 0x1, 0x7, 0x0, 0x0, 0x0, 0xc42026de20, 0x0)
	/path/to/grumpy/build/src/grumpy/object.go:64 +0xa3
grumpy/lib/test/test_support.initModule.func12(0xc42004d8f0, 0xc4204aa0f0, 0x1, 0x6, 0x6, 0xc4204aa0c0)
	/path/to/grumpy/build/src/grumpy/lib/test/test_support/module.go:2867 +0x6a7
grumpy.(*Code).Eval(0xc42037c600, 0xc42004cee0, 0xc4204f6040, 0xc4204aa0c0, 0x1, 0x6, 0x0, 0x0, 0x0, 0xc420187050, ...)
	/path/to/grumpy/build/src/grumpy/code.go:66 +0x188
grumpy.functionCall(0xc42004cee0, 0xc4201ae800, 0xc4204aa0c0, 0x1, 0x6, 0x0, 0x0, 0x0, 0x2cc734, 0xc42004cee0)
	/path/to/grumpy/build/src/grumpy/function.go:121 +0x9a
grumpy.(*Object).Call(0xc4201ae800, 0xc42004cee0, 0xc4204aa0c0, 0x1, 0x6, 0x0, 0x0, 0x0, 0x10282f0, 0x0)
	/path/to/grumpy/build/src/grumpy/object.go:64 +0xa3
grumpy/lib/test/test_support.initModule.func13(0xc42004cee0, 0xc4201655c0, 0x1, 0x8, 0x8, 0xc4200fe7d0)
	/path/to/grumpy/build/src/grumpy/lib/test/test_support/module.go:3362 +0x1f25
grumpy.(*Code).Eval(0xc42037c660, 0xc42004ce00, 0xc4204f6040, 0xc4200fe7d0, 0x1, 0x9, 0x0, 0x0, 0x0, 0x2cbdb3, ...)
	/path/to/grumpy/build/src/grumpy/code.go:66 +0x188
grumpy.functionCall(0xc42004ce00, 0xc4201ae900, 0xc4200fe7d0, 0x1, 0x9, 0x0, 0x0, 0x0, 0x277d4d, 0xc4200fe7d0)
	/path/to/grumpy/build/src/grumpy/function.go:121 +0x9a
grumpy.(*Object).Call(0xc4201ae900, 0xc42004ce00, 0xc4200fe7d0, 0x1, 0x9, 0x0, 0x0, 0x0, 0xc42002a400, 0xc420233100)
	/path/to/grumpy/build/src/grumpy/object.go:64 +0xa3
main.initModule.func21(0xc42004ce00, 0x0, 0x0, 0x0, 0x0, 0x0)
	/path/to/grumpy/a.go:57208 +0x267
grumpy.(*Code).Eval(0xc4200fd4a0, 0xc42004c0e0, 0xc420233100, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc420310000, ...)
	/path/to/grumpy/build/src/grumpy/code.go:66 +0x188
grumpy.functionCall(0xc42004c0e0, 0xc420166ac0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc42004c0e0, 0x2)
	/path/to/grumpy/build/src/grumpy/function.go:121 +0x9a
grumpy.(*Object).Call(0xc420166ac0, 0xc42004c0e0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc420346240, 0xc4200fd4a0)
	/path/to/grumpy/build/src/grumpy/object.go:64 +0xa3
main.initModule(0xc42004c0e0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/path/to/grumpy/a.go:57240 +0x12eff
grumpy.(*Code).Eval(0xc42006b620, 0xc42004c070, 0xc420233100, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x2773d8, ...)
	/path/to/grumpy/build/src/grumpy/code.go:66 +0x188
grumpy.RunMain(0xc42006b620, 0x0)
	/path/to/grumpy/build/src/grumpy/module.go:294 +0x1f8
main.main()
	/path/to/grumpy/a.go:57252 +0xa5
```

**Comment by trotterdylan** [comment]
What's around this line of code: /path/to/grumpy/a.go:18038

And what Python statements does it correspond to?

**Comment by S-YOU** [comment]
It seems like on this line 

```
if πTemp006, πE = πg.NE(πF, µbadarg, µt1); πE != nil {
```

If you uncomment on https://github.com/google/grumpy/blob/master/third_party/stdlib/test/test_datetime.py#L331
or 
https://github.com/google/grumpy/blob/master/third_party/stdlib/test/test_datetime.py#L984
You could reproduce it I guess.

**Comment by trotterdylan** [comment]
The issue turned out to be pretty obvious: https://github.com/trotterdylan/grumpy/blob/master/runtime/dict.go#L708

That should be `if !w.isInstance(DictType) {`. The fix is easy but I want to improve the dict comparison tests to make sure this case is tested. Will have a PR later today or tomorrow.
