### ISSUE TITLE
Error when running grumpy on Fedora 25

### ISSUE THREAD

**Issue by bkeys** [google/grumpy#288]
I compiled and installed from source on Fedora 25 and I get this error when I try to transpile a source file
```
Traceback (most recent call last):
  File "/usr/bin/grumpc", line 119, in <module>
    sys.exit(main(parser.parse_args()))
  File "/usr/bin/grumpc", line 77, in main
    visitor.visit(mod)
  File "/usr/lib/python2.7/site-packages/pythonparser/algorithm.py", line 41, in visit
    return self._visit_one(obj)
  File "/usr/lib/python2.7/site-packages/pythonparser/algorithm.py", line 32, in _visit_one
    return getattr(self, visit_attr)(node)
  File "/usr/lib/python2.7/site-packages/grumpy/compiler/stmt.py", line 321, in visit_Module
    self._visit_each(node.body)
  File "/usr/lib/python2.7/site-packages/grumpy/compiler/stmt.py", line 735, in _visit_each
    self.visit(node)
  File "/usr/lib/python2.7/site-packages/pythonparser/algorithm.py", line 41, in visit
    return self._visit_one(obj)
  File "/usr/lib/python2.7/site-packages/pythonparser/algorithm.py", line 32, in _visit_one
    return getattr(self, visit_attr)(node)
  File "/usr/lib/python2.7/site-packages/grumpy/compiler/stmt.py", line 292, in visit_ImportFrom
    self._write_py_context(node.lineno)
AttributeError: 'ImportFrom' object has no attribute 'lineno'
```

**Comment by trotterdylan** [comment]
What's the source file you're trying to compile?

**Comment by bkeys** [comment]
you can do this with literally any source file and it will propagate the same error

**Comment by trotterdylan** [comment]
I think I know what's going on: pythonparser is not being installed properly. When I do a fresh install and run grumpc I get:

```
grumpc
Traceback (most recent call last):
  File "/usr/bin/grumpc", line 27, in <module>
    import pythonparser
ImportError: No module named pythonparser
```

I'll come up with a fix later today.

**Comment by trotterdylan** [comment]
I think this is fixed in https://github.com/google/grumpy/pull/291

Please reopen if you continue to have problems.

**Comment by Ch3ck** [comment]
I have a similar issue here on Fedora 25: https://github.com/google/grumpy/issues/299
